left_arm:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - left_arm_a1_joint
      - left_arm_a2_joint
      - left_arm_e1_joint
      - left_arm_a3_joint
      - left_arm_a4_joint
      - left_arm_a5_joint
      - left_arm_a6_joint
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      left_arm_a1_joint: {trajectory: 0.15, goal: 0.1}
      left_arm_a2_joint: {trajectory: 0.15, goal: 0.1}
      left_arm_e1_joint: {trajectory: 0.15, goal: 0.1}
      left_arm_a3_joint: {trajectory: 0.15, goal: 0.1}
      left_arm_a4_joint: {trajectory: 0.15, goal: 0.1}
      left_arm_a5_joint: {trajectory: 0.15, goal: 0.1}
      left_arm_a6_joint: {trajectory: 0.15, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  125
    action_monitor_rate: 10
