controller_list:
  - name: fake_touch_chain_controller
    joints:
      - left_arm_a1_joint
      - left_arm_a2_joint
      - left_arm_e1_joint
      - left_arm_a3_joint
      - left_arm_a4_joint
      - left_arm_a5_joint
      - left_arm_a6_joint